language: node_js

node_js:
  - "lts/*"
  - "8"

os:
  - linux
  - osx
  - windows

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0

jobs:
  include:
    # If version.txt is updated on the master branch:
    # - create a new tag and push it to Github
    # - update the latest-release branch
    - stage: deploy
      name: "Create release on GitHub 🚀"
      os: linux
      script: echo "Checking whether we should release..."
      deploy:
      - provider: script
        script: ./create-release.sh
        on: master
      env:
        - secure: esj3ut+TwKX25QzU1koJyTVIX+x1V55graI65X8LiYXKcOP040VPJ9lIC0HeRs5UViBM0Ur1F93rGdgW2zYVzu5MLZoH7KjpzMcG30x+FDqLChT0JfNcLLtLm/wIhx/OAAmsBxXlvjPp092BeEKd3Jug8d329TxwwK5G5XxAatg=

# Automatic deploys are also enabled in Heroku for this app
# Every push to master will automatically deploy a new version of this app.
# Heroku will wait for CI to pass before deploying.

notifications:
  email: false

sudo: false
