name: Lint

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.4.0
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - run: npm install --omit=production

      - run: npm run lint
