name: Tests (Heroku)

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  test-heroku:

    name: Test kit on Heroku
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node v16
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: '16'
    - run: npm ci
    - run: npm run test:heroku
